export const TICKET_URL = 'https://ti.to/ngrome-events/ngrome-conf-mmxxiv';
export const NAV_MENU = [
  {
    name: 'Home',
    destinationUrl: '/',
    pageSite: true,
    type: 'white',
    visible: true,
  },
  {
    name: 'About',
    destinationUrl: '/about',
    type: 'white',
    visible: true,
    pageSite: true,
    icon: 'about',
  },
  {
    name: 'Sponsors',
    destinationUrl: '/sponsors',
    type: 'white',
    visible: true,
    pageSite: true,
    icon: 'sponsor',
  },
  {
    name: 'Speakers',
    destinationUrl: '/speakers',
    type: 'white',
    pageSite: true,
    visible: false,
    icon: 'speaker',
  },
  // {
  //   name: 'CFP',
  //   destinationUrl: '#callForPaper',
  //   type: 'white',
  //   pageSite: true,
  //   visible: true,
  //   icon: 'speaker',
  // },
  {
    name: "Venue",
    destinationUrl: "/venue",
    type: "white",
    visible: true,
    pageSite: true,
    icon: 'venue',
  },
  //{
  //   name: 'Info',
  //   destinationUrl: '/info',
  //   type: 'white',
  //   visible: true,
  // },
  // {
  //   name: 'Blog',
  //   destinationUrl: '/blog',
  //   type: 'white',
  //   visible: false,
  // },
  {
    name: 'Workshops',
    destinationUrl: '/workshops',
    type: 'white',
    pageSite: true,
    visible: true,
    icon: 'workshop',
  },
  {
    pastEdition: true,
    name: '2022',
    destinationUrl: 'https://2022.ngrome.io',
    type: 'white',
    pageSite: false,
    visible: true,
  },
  {
    pastEdition: true,
    name: '2023',
    destinationUrl: 'https://2023.ngrome.io',
    type: 'white',
    visible: true,
    pageSite: false,
  },
];
