export const FOOTER_MENU = [
  {
    name: 'Code of Conduct',
    destinationUrl: './code-of-conduct',
    type: 'link',
    visible: true,
  },
  {
    name: 'Terms & Privacy',
    destinationUrl: './terms-and-privacy',
    type: 'link',
    visible: true,
  },
  {
    name: 'About',
    destinationUrl: './about',
    type: 'link',
    visible: true,
  },
  // {
  //   name: 'Diversity',
  //   destinationUrl: './',
  //   type: 'link',
  //  visible: true,
  // },
  {
    name: 'Sponsors',
    destinationUrl: './sponsors',
    type: 'link',
    visible: false,
  },
  {
    name: 'Speakers',
    destinationUrl: './speakers',
    type: 'link',
    visible: false,
  },
  {
    name: 'Workshops',
    destinationUrl: './workshops',
    type: 'link',
    visible: false,
  },
  {
    name: 'Agenda',
    destinationUrl: './agenda',
    type: 'link',
    visible: false,
  },

  {
    name: 'Media Kit',
    destinationUrl: './media-kit',
    type: 'link',
    visible: true,
  },
  {
    name: '2022',
    destinationUrl: 'https://2022.ngrome.io',
    type: 'link',
    pageSite: false,
    visible: true,
  },
  {
    pastEdition: true,
    name: '2023',
    destinationUrl: 'https://2023.ngrome.io',
    type: 'link',
    visible: true,
    pageSite: false,
  },
  {
    pastEdition: true,
    name: '2024',
    destinationUrl: '/2024',
    type: 'link',
    visible: true,
    pageSite: false,
  },
];
