import { defineEventHandler } from 'h3';
import { Agenda } from 'src/app/models/agenda.model';

export default defineEventHandler(() => agendaList);

const agendaList: Agenda[] = [
  {
    startTime: '08:00',
    duration: 60,
    endTime: '09:00',
    type: 'Registration & Welcome coffee',
    speaker: '',
    title: '',
  },
  {
    startTime: '09:00',
    duration: 20,
    endTime: '09:20',
    type: 'Opening Remarks',
    speaker: 'NGRome Team',
    title: '',
  },
  {
    startTime: '09:20',
    duration: 40,
    endTime: '10:00',
    type: 'Opening Keynote',
    speaker: 'Alex Okrushko, Marko Stanimirović, Brandon Roberts',
    title: '',
  },
  {
    startTime: '10:00',
    duration: 25,
    endTime: '10:25',
    type: 'Talk 1',
    speaker: 'Enea Jahollari',
    title: 'A change detection, zone.js and signals story',
  },
  {
    startTime: '10:25',
    duration: 10,
    endTime: '10:35',
    type: 'Lighting Talk 1',
    speaker: 'Christopher Holder',
    title: '',
  },
  {
    startTime: '10:35',
    duration: 15,
    endTime: '10:50',
    type: 'Panel',
    speaker: '',
    title: '',
  },
  {
    startTime: '10:50',
    duration: 40,
    endTime: '11:30',
    type: 'Coffee break',
    speaker: '',
    title: '',
  },
  {
    startTime: '11:30',
    duration: 5,
    endTime: '11:35',
    type: 'Sponsor pitch',
    speaker: '',
    title: '',
  },
  {
    startTime: '11:35',
    duration: 25,
    endTime: '12:00',
    type: 'Talk 3',
    speaker: 'Manfred Steyer',
    title: 'Jurassic Script: When One-Liners Ruled the Earth',
  },
  {
    startTime: '12:00',
    duration: 10,
    endTime: '12:10',
    type: 'Lighting Talk 2',
    speaker: '',
    title: '',
  },
  {
    startTime: '12:10',
    duration: 25,
    endTime: '12:35',
    type: 'Talk 4',
    speaker: 'Alisa Duncan',
    title: 'Valuable Component Testing in Angular',
  },
  {
    startTime: '12:35',
    duration: 25,
    endTime: '13:00',
    type: 'Talk 5',
    speaker: '',
    title: '',
  },
  {
    startTime: '13:00',
    duration: 15,
    endTime: '13:15',
    type: 'Panel',
    speaker: '',
    title: '',
  },
  {
    startTime: '13:15',
    duration: 55,
    endTime: '14:10',
    type: 'Lunch',
    speaker: '',
    title: '',
  },
  {
    startTime: '14:10',
    duration: 10,
    endTime: '14:20',
    type: 'Sponsor pitch',
    speaker: '',
    title: '',
  },
  {
    startTime: '14:20',
    duration: 25,
    endTime: '14:45',
    type: 'Talk 6',
    speaker: 'Natalia Venditto',
    title: 'Long Road to Reusable Design System in Angular #2',
  },
  {
    startTime: '14:45',
    duration: 25,
    endTime: '15:10',
    type: 'Talk 7',
    title: '',
    speaker: 'Brandon Roberts',
  },
  {
    startTime: '15:10',
    duration: 10,
    endTime: '15:20',
    type: 'Lightning Talk 3',
    speaker: 'Daniela Bonvini',
    title: "Angular Signals: what's all the fuss about?",
  },
  {
    startTime: '15:20',
    duration: 25,
    endTime: '15:45',
    type: 'Talk 8',
    title: '',
    speaker: 'Alessandro Millucci',
  },
  {
    startTime: '15:45',
    duration: 15,
    endTime: '16:00',
    type: 'Panel',
    speaker: '',
    title: '',
  },
  {
    startTime: '15:45',
    duration: 40,
    endTime: '16:25',
    type: 'Coffee break',
    speaker: '',
    title: '',
  },
  {
    startTime: '16:00',
    duration: 10,
    endTime: '16:10',
    type: 'Sponsor pitch',
    speaker: '',
    title: '',
  },
  {
    startTime: '16:10',
    duration: 25,
    endTime: '16:35',
    type: 'Talk 10',
    speaker: 'Soumaya Erradi',
    title: 'State of SSR with Angular',
  },
  {
    startTime: '16:35',
    duration: 10,
    endTime: '16:45',
    type: 'Lightning Talk 4',
    speaker: '',
    title: '',
  },
  {
    startTime: '16:45',
    duration: 25,
    endTime: '17:10',
    type: 'Talk 12',
    title: '',
    speaker: 'Mateusz Łędzewicz',
  },
  {
    startTime: '17:10',
    duration: 40,
    endTime: '17:50',
    type: 'Closing Keynote',
    title: '',
    speaker: 'Mike Ryan?',
  },
  {
    startTime: '17:50',
    duration: 25,
    endTime: '18:15',
    type: 'Closing Remarks',
    speaker: '',
    title: '',
  },
];
